service: backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-west-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    JWT_SECRET: ${env:JWT_SECRET, 'default-secret-change-me'}
    DYNAMO_ENDPOINT: ${self:custom.dynamoEndpoint.${opt:stage, self:provider.stage}}
    NODE_ENV: ${opt:stage, self:provider.stage, 'dev'}

  iam: ${file(./serverless-resources/iam.yml)}

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources: ${file(./serverless-resources/dynamo.yml)}


custom:
  dynamoEndpoint:
    dev: "http://127.0.0.1:8000"
    prod: ""
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: []
    target: node20
    platform: node
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
